#!/usr/bin/env sh

# ==============================================================================
#
# Script name: start
# Description: Script used to toggle gsimplecal (meant to be used by the fire
#              tool).
# Dependencies: pkill, pidof, gsimplecal
# GitHub: https://www.github.com/mathieuhardy/nixos
# License: https://www.github.com/mathieuhardy/nixos/LICENSE
# Contributors: Mathieu Hardy
#
# ==============================================================================

# ------------------------------------------------------------------------------
# Dependencies
# ------------------------------------------------------------------------------

if ! command -v pkill >/dev/null
then
    echo "Missing 'pkill'" 1>&2
    exit 1
fi

if ! command -v pidof >/dev/null
then
    echo "Missing 'pidof'" 1>&2
    exit 1
fi

if ! command -v gsimplecal >/dev/null
then
    echo "Missing 'gsimplecal'" 1>&2
    exit 1
fi

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

binary=gsimplecal

# ------------------------------------------------------------------------------
# Entry point
# ------------------------------------------------------------------------------

if [ $(pidof ${binary}) ]
then
    pkill -x ${binary}
else
    ${binary} &
fi
