#!/usr/bin/env bash

# ==============================================================================
#
# Script name: start
# Description: Script used to start polybar (meant to be used by the fire tool).
# Dependencies: polybar
# GitHub: https://www.github.com/mathieuhardy/nixos
# License: https://www.github.com/mathieuhardy/nixos/LICENSE
# Contributors: Mathieu Hardy
#
# ==============================================================================

# ------------------------------------------------------------------------------
# Dependencies
# ------------------------------------------------------------------------------

if ! command -v polybar >/dev/null
then
    echo "Missing 'polybar'" 1>&2
    exit 1
fi

# ------------------------------------------------------------------------------
# Entry point
# ------------------------------------------------------------------------------

for monitor in $(polybar --list-monitors | cut -d":" -f1)
do
    MONITOR="${monitor}" polybar top &
    MONITOR="${monitor}" polybar bottom &
done
