#!/usr/bin/env sh

# ==============================================================================
#
# Script name: stop
# Description: Script used to stop polybar (meant to be used by the fire tool).
# Dependencies: pkill
# GitHub: https://www.github.com/mathieuhardy/nixos
# License: https://www.github.com/mathieuhardy/nixos/LICENSE
# Contributors: Mathieu Hardy
#
# ==============================================================================

# ------------------------------------------------------------------------------
# Dependencies
# ------------------------------------------------------------------------------

if ! command -v pkill >/dev/null
then
    echo "Missing 'pkill'" 1>&2
    exit 1
fi

# ------------------------------------------------------------------------------
# Entry point
# ------------------------------------------------------------------------------

pkill -x polybar
